version: "3.5"
services:

  dashdot:
    container_name: dashdot
    image: mauricenino/dashdot:latest
    privileged: true
    restart: always
    environment:
      - DASHDOT_ENABLE_TILT=true
      - DASHDOT_DISABLE_HOST=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
    volumes:
      - /sys/class/net/ens18:/mnt/eth0:ro
      - /etc/os-release:/etc/os-release:ro
      - /proc/1/ns/net:/mnt/host_ns_net:ro
      - /media:/mnt/host_media:ro
      - /mnt:/mnt/host_mnt:ro
    ports:
      - '3001:3001'
    
  wetty:
    container_name: wetty
    image: wettyoss/wetty:latest
    privileged: true
    restart: always
    network_mode: bridge
    environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/New_York
          - SSH-USER=user
          - SSH-PASS=password
    ports:
      - '3000:3000'
  
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    restart: always
    network_mode: bridge
    environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/New_York
    volumes:
      - type: bind
        source: /config/uptime-kuma
        target: /app/data
    ports:
      - '3002:3001'
