version: "3"
services:

  dashdot:
    container_name: dashdot
    image: mauricenino/dashdot:latest
    privileged: true

    restart: unless-stopped
    network_mode: bridge
    environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/New_York
          - DASHDOT_ENABLE_TILT=true
          - DASHDOT_OS_WIDGET_ENABLE=false
          - DASHDOT_ENABLE_CPU_TEMPS=true
    ports:
      - '3001:3001'
