version: "3.4"
services:

    motioneye:
        container_name: motioneye
        image: ccrisan/motioneye:master-amd64
        restart: unless-stopped
        network_mode: bridge
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/New_York
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/motioneye:/etc/motioneye
            - /var/lib/motioneye:/var/lib/motioneye
        ports:
          - 8765:8765
