version: '2.4'
services:

  libreddit:
    container_name: libreddit
    image: spikecodes/libreddit
    restart: unless-stopped
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/libreddit:/config
    ports:
      - 1337:8080

  whoogle-search:
    container_name: whoogle-search
    image: benbusby/whoogle-search:latest
    restart: unless-stopped
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    user: whoogle
    volumes:
      - /config/whoogle-search:/config
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=10M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    ports:
      - 5000:5000

  code-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/code-server:/config
      - /config:/shared-access
    ports:
      - 9123:8443

  homer:
    container_name: homer
    image: b4bz/homer:latest
    restart: unless-stopped
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/homer:/www/assets
    ports:
      - 8080:8080
      
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/filebrowser/database.db:/database.db
      - /config/filebrowser/.filebrowser.json:/.filebrowser.json
      - /:/srv
    ports:
      - 8899:80
